import {
    FaBarcode,
    FaCheckCircle,
    FaBoxOpen,
    FaSortAmountDown,
    FaUndoAlt,
    FaChartBar,
    FaBoxes,
    FaArrowsAltV,
    FaTags,
    FaTruckMoving,
    FaTshirt,
    FaPuzzlePiece,
} from "react-icons/fa";

export const valueAddedServices = [
    {
        id: 1,
        image: "/assets/Services/VAS/scanning.jpg",
        icon: FaBarcode,
        title: "Scanning",
        desc: "The scanning of cargo in accordance to your requirements to be performed.",
    },
    {
        id: 2,
        image: "/assets/Services/VAS/quality-controls.jpg",
        icon: FaCheckCircle,
        title: "Quality Controls",
        desc: "We can assist on performing operational techniques and activities on cargo to fulfil your quality requirements.",
    },
    {
        id: 3,
        image: "/assets/Services/VAS/repackaging.jpg",
        icon: FaBoxOpen,
        title: "Re-packaging",
        desc: "We assist you with packing or re-packing of cargo based on specified requirements.",
    },
    {
        id: 4,
        image: "/assets/Services/VAS/cargo-sorting.jpg",
        icon: FaSortAmountDown,
        title: "Cargo sorting",
        desc: "Sorting of cargo based on your requirements could be performed at our facilities.",
    },
    {
        id: 5,
        image: "/assets/Services/VAS/return-management.jpg",
        icon: FaUndoAlt,
        title: "Returns management",
        desc: "We can support your operation by managing your goods return flows into the warehouse.",
    },
    {
        id: 6,
        image: "/assets/Services/VAS/reporting.jpg",
        icon: FaChartBar,
        title: "Reporting",
        desc: "We can bring visibility on your inventory through the creation of customized reports.",
    },
    {
        id: 7,
        image: "/assets/Services/VAS/palletizing.jpg",
        icon: FaBoxes,
        title: "Palletizing",
        desc: "We can support with the storing and transporting of cargo stacked on pallets.",
    },
    {
        id: 8,
        image: "/assets/Services/VAS/shaving.jpg",
        icon: FaArrowsAltV,
        title: "Shaving/topping off pallets",
        desc: "Adjusting the height of a pallet by removing the upper layer(s) of cartons.",
    },
    {
        id: 9,
        image: "/assets/Services/VAS/labelling.jpg",
        icon: FaTags,
        title: "Labelling",
        desc: "The printing and placing of labels according to your requirements.",
    },
    {
        id: 10,
        image: "/assets/Services/VAS/yard-management.jpg",
        icon: FaTruckMoving,
        title: "Yard management",
        desc: "At our facilities trucks/containers at the yard could be managed effectively.",
    },
    {
        id: 11,
        image: "/assets/Services/VAS/garmnets.jpg",
        icon: FaTshirt,
        title: "Garments on hangers",
        desc: "Our facilities are equipped to handle hanging garments on racks/rails.",
    },
    {
        id: 12,
        image: "/assets/Services/VAS/customization.jpg",
        icon: FaPuzzlePiece,
        title: "Product customization",
        desc: "Our customization services allow you to bundle precisely to your needs.",
    },
];
